/******************************************************************************/
/***          Generated by IBExpert 2012.02.21 20/01/2019 10:39:04          ***/
/******************************************************************************/

/******************************************************************************/
/***      Following SET SQL DIALECT is just for the Database Comparer       ***/
/******************************************************************************/
SET SQL DIALECT 3;



/******************************************************************************/
/***                               Generators                               ***/
/******************************************************************************/

CREATE GENERATOR GEN_CONTA_ID;
SET GENERATOR GEN_CONTA_ID TO 6;

CREATE GENERATOR GEN_GRUPO_ID;
SET GENERATOR GEN_GRUPO_ID TO 77;

CREATE GENERATOR GEN_MOVIMENTO_ID;
SET GENERATOR GEN_MOVIMENTO_ID TO 5;



/******************************************************************************/
/***                                 Tables                                 ***/
/******************************************************************************/



CREATE TABLE CONTA (
    ID        INTEGER NOT NULL,
    NOME      VARCHAR(50) NOT NULL,
    GRUPO_ID  INTEGER NOT NULL,
    TIPO      CHAR(1) NOT NULL
);

CREATE TABLE GRUPO (
    ID    INTEGER NOT NULL,
    NOME  VARCHAR(50) NOT NULL
);

CREATE TABLE MOVIMENTO (
    ID         INTEGER NOT NULL,
    DATA       DATE NOT NULL,
    CONTA_ID   INTEGER NOT NULL,
    TIPO       CHAR(1) NOT NULL,
    VALOR      FLOAT NOT NULL,
    HISTORICO  VARCHAR(255) NOT NULL
);



/******************************************************************************/
/***                           Unique Constraints                           ***/
/******************************************************************************/

ALTER TABLE CONTA ADD CONSTRAINT UNQ_CONTA UNIQUE (NOME);
ALTER TABLE GRUPO ADD CONSTRAINT UNQ_GRUPO UNIQUE (NOME);


/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE CONTA ADD CONSTRAINT PK_CONTA PRIMARY KEY (ID);
ALTER TABLE GRUPO ADD CONSTRAINT PK_GRUPO PRIMARY KEY (ID);
ALTER TABLE MOVIMENTO ADD CONSTRAINT PK_MOVIMENTO PRIMARY KEY (ID);


/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE CONTA ADD CONSTRAINT FK_CONTA_GRUPO FOREIGN KEY (GRUPO_ID) REFERENCES GRUPO (ID);
ALTER TABLE MOVIMENTO ADD CONSTRAINT FK_MOVIMENTO_CONTA FOREIGN KEY (CONTA_ID) REFERENCES CONTA (ID);


/******************************************************************************/
/***                                Triggers                                ***/
/******************************************************************************/


SET TERM ^ ;



/******************************************************************************/
/***                          Triggers for tables                           ***/
/******************************************************************************/



/* Trigger: CONTA_BI */
CREATE TRIGGER CONTA_BI FOR CONTA
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_conta_id,1);
end
^

/* Trigger: GRUPO_BI */
CREATE TRIGGER GRUPO_BI FOR GRUPO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_grupo_id,1);
end
^

/* Trigger: MOVIMENTO_BI */
CREATE TRIGGER MOVIMENTO_BI FOR MOVIMENTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_movimento_id,1);
end
^

SET TERM ; ^

